ui_print " "
ui_print " - ADDITIONAL OPTION -"
ui_print " *******************************************"
ui_print " "
ui_print "      - Weather install ..."
ui_print "      - Widget install..."
ui_print "      - IconPack  install..."
ui_print "      - Launcher install..."
ui_print "      - Fonts install..."
ui_print " "
ui_print "      Install successful..."